### ISSUE TITLE
ciao: move steps on how to setup ansible to development page

### ISSUE THREAD

**Issue by albertomurillo** [clearlinux/clear-config-management#102]
The current documentation instruct the user to download go, ansible and setup all the dependencies himself.

The documentation should minimize the number of steps by having the user use the ciao-deploy container which already has all the dependencies installed.

The steps on how to setup ansible and its dependencies should be moved to the development page.

**Comment by mrkz** [comment]
Which would be the benefit of having all the ansible, go, etc install instructions into the development page?

To my understanding, that's neither helpful nor required for a proper **development** setup but would confuse users instead as it would state different instructions as the ones provided on the README.md
Plus, that'd add a maintenance cost as we would need to update that documentation every time the instructions for the docker container image changes.

We could inform about the `Dockerfile` and it's `README.md` used instead, that way if a user wants to know more about the container, can take a direct look into the `Dockerfile` used

**Comment by albertomurillo** [comment]
This is tracked at https://github.com/01org/ciao/pull/795
