### ISSUE TITLE
fail to mount cnci image in bare metal

### ISSUE THREAD

**Issue by arturo-garcia-garcia** [clearlinux/clear-config-management#103]
When running command "ansible-playbook  -i hosts ciao.yml  --private-key=~/.ssh/id_rsa --user=root" in the ciao-deploy container, it fails at this step

`
TASK [clearlinux.ciao-controller : Mounting cnci image in /mnt/tmp] ************
task path: /etc/ansible/roles/clearlinux.ciao-controller/tasks/create_cnci_image.yml:51
<controller.example.com> ESTABLISH LOCAL CONNECTION FOR USER: root
<controller.example.com> EXEC /bin/sh -c 'LANG=en_US.UTF-8 LC_ALL=en_US.UTF-8 LC_MESSAGES=en_US.UTF-8 /usr/bin/python && sleep 0'
fatal: [controller.example.com]: FAILED! => {"changed": false, "failed": true, "invocation": {"module_args": {"dump": null, "fstab": "/etc/fstab", "fstype": "ext4", "name": "/mnt/tmp", "opts": null, "passno": null, "src": "/dev/loop2p2", "state": "mounted"}, "module_name": "mount"}, "msg": "Error mounting /mnt/tmp: mount: special device /dev/loop2p2 does not exist\n"}
`

this are the loop devices as listed on the container

`root@f91fceb04390 /root/ciao # losetup
NAME       SIZELIMIT OFFSET AUTOCLEAR RO BACK-FILE                                        DIO
/dev/loop0         0      0         0  0 /root/ciao/images/clear-8260-ciao-networking.img   0
`

This is run in a cluster of 4 NUCs, this is the host file
root@f91fceb04390 /root/ciao # cat hosts 
[controllers]
controller.example.com

[networks]
network.example.com

[computes]
compute01.example.com
compute02.example.com

**Comment by arturo-garcia-garcia** [comment]
I just try to run the installation on the host, straigth from the configuration that is pass to the container  ($(pwd)/clear-config-management/examples/ciao) and it ends sucesfuly

**Comment by albertomurillo** [comment]
The issues are now mantained at github.com/01org/ciao
Please open the issue there
