### ISSUE TITLE
ciao-cli node list -compute returns error

### ISSUE THREAD

**Issue by arturo-garcia-garcia** [clearlinux/clear-config-management#104]
After install ciao in a 4 nucs cluster from the configuration created at "(pwd)/clear-config-management/examples/ciao" (not using the container), ansible reply success, but after source the generated files "admin-ciaorc" and "openrc" when trying to list he nodes, got this error

`
root@controller.example.com ~/cloud/clear-config-management/examples/ciao # source admin-ciaorc 

root@controller.example.com ~/cloud/clear-config-management/examples/ciao # source openrc 

root@controller.example.com ~/cloud/clear-config-management/examples/ciao # ciao-cli node list -compute
E1109 23:38:13.002075   30742 authenticate.go:43] ciao-cli ERROR: Could not get AuthenticatedClient Post https://controller.example.com:35357/v3/auth/tokens: dial tcp 10.64.153.159:35357: getsockopt: connection refused
E1109 23:38:13.002345   30742 identity.go:126] ciao-cli ERROR: Failed to create an AuthenticatedClient
E1109 23:38:13.154504   30742 main.go:220] ciao-cli ERROR: Could not send HTTP request Get https://controller.example.com:8774/v2.1/nodes: dial tcp 10.64.153.159:8774: getsockopt: connection refused
F1109 23:38:13.154541   30742 node.go:123] ciao-cli FATAL: Get https://controller.example.com:8774/v2.1/nodes: dial tcp 10.64.153.159:8774: getsockopt: connection refused
goroutine 1 [running]:
github.com/01org/ciao/vendor/github.com/golang/glog.stacks(0x8feb00, 0xc400000000, 0xa6, 0x124)
	/builddir/build/BUILD/ciao-62/src/github.com/01org/ciao/vendor/github.com/golang/glog/glog.go:769 +0xa5
github.com/01org/ciao/vendor/github.com/golang/glog.(*loggingT).output(0x8e2820, 0xc400000003, 0xc4200d20c0, 0x8bd491, 0x7, 0x7b, 0x0)
	/builddir/build/BUILD/ciao-62/src/github.com/01org/ciao/vendor/github.com/golang/glog/glog.go:720 +0x357
github.com/01org/ciao/vendor/github.com/golang/glog.(*loggingT).printDepth(0x8e2820, 0xc400000003, 0x1, 0xc4200e9b68, 0x1, 0x1)
	/builddir/build/BUILD/ciao-62/src/github.com/01org/ciao/vendor/github.com/golang/glog/glog.go:646 +0x126
github.com/01org/ciao/vendor/github.com/golang/glog.FatalDepth(0x1, 0xc4200e9b68, 0x1, 0x1)
	/builddir/build/BUILD/ciao-62/src/github.com/01org/ciao/vendor/github.com/golang/glog/glog.go:1134 +0x5d
main.fatalf(0xc420056ee0, 0x6a, 0x0, 0x0, 0x0)
	/builddir/build/BUILD/ciao-62/src/github.com/01org/ciao/ciao-cli/main.go:127 +0x126
main.listComputeNodes(0x0, 0x9, 0x0)
	/builddir/build/BUILD/ciao-62/src/github.com/01org/ciao/ciao-cli/node.go:123 +0x9dc
main.(*nodeListCommand).run(0xc420018600, 0xc42000c2b0, 0x0, 0x0, 0xc42000c2b0, 0x0)
	/builddir/build/BUILD/ciao-62/src/github.com/01org/ciao/ciao-cli/node.go:107 +0xdb
main.(*command).run(0x8e0de8, 0xc42000c2b0, 0x0, 0x0, 0xc42008d868, 0x0)
	/builddir/build/BUILD/ciao-62/src/github.com/01org/ciao/ciao-cli/main.go:55 +0x15b
main.main()
	/builddir/build/BUILD/ciao-62/src/github.com/01org/ciao/ciao-cli/main.go:401 +0xf7
root@controller.example.com ~/cloud/clear-config-management/examples/ciao # 
` 

here is the "admin-ciaorc" file

`
root@controller.example.com ~/cloud/clear-config-management/examples/ciao # cat admin-ciaorc 
export CIAO_CONTROLLER=controller.example.com
export CIAO_IDENTITY=https://controller.example.com:35357
export CIAO_USERNAME=admin
export CIAO_PASSWORD=adminUserPassword
export CIAO_TENANT_NAME=admin

`

here is the "openrc" file

`
root@controller.example.com ~/cloud/clear-config-management/examples/ciao # cat openrc 

export OS_PROJECT_DOMAIN_ID=default
export OS_USER_DOMAIN_ID=default
export OS_PROJECT_NAME=admin
export OS_TENANT_NAME=admin
export OS_USERNAME=admin
export OS_PASSWORD=adminUserPassword
export OS_AUTH_URL=https://controller.example.com:35357/v3
export OS_CACERT=certificates/keystone/keystone_cert.pem
export OS_IDENTITY_API_VERSION=3
export OS_IMAGE_API_VERSION=2
`

**Comment by albertomurillo** [comment]
The playbooks are now mantained at github.com/01org/ciao
Please open an issue there

**Comment by arturo-garcia-garcia** [comment]
@albertomurillo ok, I'll open this issue in github.com/01org/ciao
Thanks
