### ISSUE TITLE
Ciao installation issues

### ISSUE THREAD

**Issue by markdryan** [clearlinux/clear-config-management#37]
1. Please clarify which version of python needs to be installed on the nodes.  Also are any additional modules required on python.
2. Please add instructions for the development mode.  I assume that the deployment machine needs to be a linux machine.  If so please specify this.
3. When I didn't specify the --extra-vars="ciao_dev=true" the install failed.  Where does the playbook expect to find the binaries if they are not already compiled.
4. I had enormous problems with proxies on both the deployment machines and the nodes.  Here's what I did to get things working on Ubuntu.  Please add to instructions.
   - Add --ignore certs to the ansible-galaxy install command on Ubuntu (deployment machine was running behind a proxy).  The command failed even though I had my proxies set up.
   - Make sure the nodes are in your no_proxy environment variable on the deployment machine.  If you don't do this the keystone checks from the deployment machine fail.
   - Created a file called /etc/apt/apt.conf.d/00proxy with the following contents on each node
     Acquire::http::Proxy "http://proxy-address:port";
     Acquire::https::Proxy "https://proxy-address:port";
   - initialised http_proxy and https_proxy in /etc/environment on each node.  This was needed for the image downloads.
5. ansible-galaxy install needed to be run as root on Ubuntu.  This isn't mentioned in the instructions.
6. passwordless sudo needs to be enabled for the installation user on the deployment machine.  I don't see this noted anywhere.  Well it's sort of mentioned in the first line but it's unclear.

**Comment by albertomurillo** [comment]
--ignore-certs issue will be handled in https://github.com/clearlinux/clear-config-management/issues/49

proxy issues will be handled in https://github.com/clearlinux/clear-config-management/issues/47

The rest of the issues mentioned here will be handled in https://github.com/clearlinux/clear-config-management/pull/48

**Comment by albertomurillo** [comment]
1) PR #48 Adds a link to official ansible documentatino that explains required python version on managed hosts.
2) The deployemnt machine has to be a linux OS as already specified in "Deployment machine" section
3) Please open a new issue on why it failed. The playbooks tries to install ciao from OS packages (swupd for clearlinux,
   dnf for fedora, apt-get for ubuntu)
4) A new issue has been opened to track and document all proxy issues. https://github.com/clearlinux/clear-config-management/issues/47
5) PR #48 Specifies which commands have to be run as sudo 
6) PR #48 specifies passwordless sudo is required for the managed nodes and the deployment node

**Comment by markdryan** [comment]
@albertomurillo Okay, fair enough.  I just have one remaining comment on the setence about passwordless ssh and sudo access and then the PR is good for me.  I'll see if I can reproduce the failure when ciao_dev is not specified.
