### ISSUE TITLE
It's not possible to restart the playbook from a given stage

### ISSUE THREAD

**Issue by markdryan** [clearlinux/clear-config-management#38]
So for example, running the command:

ansible-playbook  -vvv --extra-vars="ciao_dev=true" -i hosts --start-at-task="Download ClearLinux Image" ciao.yml

gives me this error

```
TASK [clearlinux.ciao-controller : Install CIAO binaries] **********************
task path: /etc/ansible/roles/clearlinux.ciao-controller/tasks/install.yml:16
fatal: [cnw-ctl]: FAILED! => {"failed": true, "msg": "the field 'args' has an invalid value, which appears to include a variable that is undefined. The error was: 'bindir' is undefined\n\nThe error appears to have been in '/etc/ansible/roles/clearlinux.ciao-controller/tasks/install.yml': line 16, column 5, but may\nbe elsewhere in the file depending on the exact syntax problem.\n\nThe offending line appears to be:\n\n\n  - name: Install CIAO binaries\n    ^ here\n"}
```

**Comment by albertomurillo** [comment]
This is not a good way to run the playbook since there are tasks to define facts depending on the state of the system.

To run the playbook in parts you could for example:

ansible-playbook -i hosts ciao_controllers.yml
ansible-playbook -i hosts ciao_networks.yml
ansible-playbook -i hosts ciao_computes.yml

**Comment by markdryan** [comment]
But what should people do if the script fails and they need to restart? This happens a lot the first time you try it as there are lots of things to set up.  Is there any way to restart from the last known good position?

**Comment by albertomurillo** [comment]
So the whole idea behind ansible and other configuration management tools is "idempotency".
where you can just run everything and if the change was already applied, it wont do anything in the second run.

**Comment by markdryan** [comment]
Okay, so essentially we shouldn't be doing this.  Thanks for the clarification.  I'll close this ticket.
