### ISSUE TITLE
ciao: ciao-webui container doesn't work on Ubuntu

### ISSUE THREAD

**Issue by markdryan** [clearlinux/clear-config-management#39]
The problem is that docker gets its dns information from the /etc/resolv.conf file on the host.  But if your host is running Ubuntu, resolv.conf does not contain the dns server.  So this means that the web ui cannot access the controller, and it simply hangs.  You can get to the log in page but the UI hangs as soon as you enter you credentials, presumably as the webui cannot contact the controller.

**Comment by markdryan** [comment]
I guess we just need to add to the instructions that you need to modify network managers conf from updating DNS

**Comment by albertomurillo** [comment]
There is a variable to define a dictionary of hostmappings in 
https://github.com/clearlinux/clear-config-management/blob/master/roles/ciao-webui/defaults/main.yml#L22-L23

Obviously this has to be mentioned in the documentation with an example.

**Comment by markdryan** [comment]
The thing is that this is not just a web-ui container problem.  This will also affect all containers launched by launcher on the cns.  So we need to mention in the instructions that network managers resolv.conf code needs to be disabled.

We're going to have to have an Ubuntu section that explains all the proxy stuff you need to do, so we can add this in here.
