### ISSUE TITLE
launcher: The logs should be written to /var/lib/ciao/logs

### ISSUE THREAD

**Issue by albertomurillo** [clearlinux/clear-config-management#44]

**Comment by albertomurillo** [comment]
Currently, we dont have logrotate policies to prevent the log files from filling the disk.
systemd journal handles this automatically. this is why we log to system

**Comment by sofar** [comment]
We should never log to /var/lib anyway, especially if systemd-journald is running. Logs should be in /var/log instead, but please continue to log to the journal.

**Comment by albertomurillo** [comment]
@markdryan any objections before i close this issue as per @sofar comments?
