### ISSUE TITLE
ciao: examples: ansible-galaxy install fails in clearlinux

### ISSUE THREAD

**Issue by albertomurillo** [clearlinux/clear-config-management#49]
When running ansible-galaxy install -r requirements.txt behind a proxy in clearlinux it fails as follows

```
# sudo -E ansible-galaxy install -r requirements.yml  -f
 [WARNING]: - clearlinux.docker was NOT installed successfully: The API server (https://galaxy.ansible.com/api/) is not responding, please
try again later

ERROR! - you can use --ignore-errors to skip failed roles and finish processing the list.
```

**Comment by markdryan** [comment]
I get the same error on Ubuntu 16.04 desktop.

**Comment by obedmr** [comment]
Need to identify where is the issue, it seems like the issue is on ClearLinux,
@mrkz could you please  share your finding here?

**Comment by albertomurillo** [comment]
This isn't a bug in the documentation or the playbooks. But we stilll need to figure out whats wrong.

**Comment by albertomurillo** [comment]
Since ClearLinux 10900 there is /etc/ssl/certs symlink to /var/cache/ca-certs which fixes the issue.
For ubuntu, the system might have missing certificates

**Comment by albertomurillo** [comment]
I am unable to reproduce on ubuntu 16.04
@markdryan are you still having issues? do you have ca-certificates package installed?

**Comment by markdryan** [comment]
It's working for me now as well, although I'm pretty sure it wasn't working last week.  Anyway we can close this issue I guess.
