### ISSUE TITLE
ciao: Ansible playbook can't  add the storage-cluster  bundle on Network Node 

### ISSUE THREAD

**Issue by chuyd** [clearlinux/clear-config-management#52]
ciao-network.service can not add the storage-cluster bundle on the network node

OS Detected: clearlinux
Missing packages detected: [storage-cluster]
Failed to install: storage-cluster

The playbook ciao.yml  was executed on fedora 24

**Comment by obedmr** [comment]
This is a proxies issue, will be addressed on separated section #65

**Comment by albertomurillo** [comment]
This is swupd not reaching swupd servers due to proxies issues.
This will be handled by point 5 in https://github.com/clearlinux/clear-config-management/issues/47
