### ISSUE TITLE
ansible: ciao.yml playbook can not copy files if  "/etc/systemd/system/" directory does not exist

### ISSUE THREAD

**Issue by chuyd** [clearlinux/clear-config-management#53]
If /etc/systemd/system directory does not exist, the playbook ciao.yml fails to scp files. Once  the path was created manually and the playbook ciao.yml can copy the files.

**Comment by albertomurillo** [comment]
In which case /etc/systemd/system wouldn't exist?

**Comment by bryteise** [comment]
On Sep 23, 2016 4:19 PM, "Alberto Murillo" notifications@github.com wrote:

> In which case /etc/systemd/system wouldn't exist?

On Clear it would not exist by default without some manual user setting.

**Comment by albertomurillo** [comment]
This folder is usually created when enabling ssh or setting up docker proxies.

Anyways, it doesn't hurt to check for its existence.
