### ISSUE TITLE
ansible:  playbook can not copy files using sftp on fedora 24

### ISSUE THREAD

**Issue by chuyd** [clearlinux/clear-config-management#54]
Ansible fails to copy files using sftp on fedora 24. ansible uses sftp instead scp on fedora 24.

**Comment by albertomurillo** [comment]
This issue is a bit miss-stated.

Ansible uses sftp by default in fedora and ubuntu
ClearLinux has sftp disabled by default.

The issue appears when the deployment machine is either ubuntu or fedora and the managed node is clearlinux
