### ISSUE TITLE
ciao: Useful to have a tested/working requirements.txt file for python dependencies

### ISSUE THREAD

**Issue by obedmr** [clearlinux/clear-config-management#59]
The generic example's pip install doesn't list versions for the packages it requires (it'd be nice if you could throw that in a curlable requirements.txt in the documentation too). Otherwise this I'd just add the playbook edits to really run and it looks good. Again having a screencast would be very handy as well.

https://github.com/clearlinux/clear-config-management/tree/master/examples/ciao

```
sudo pip install netaddr docker-py python-keystoneclient
```

**Comment by albertomurillo** [comment]
IF we change the documentation to use the ciao-deploy container, then this issue is invalid.

**Comment by albertomurillo** [comment]
We are shipping a container with all depdendencies resolved.
