### ISSUE TITLE
ciao: Create a separate document for ciao deployment for developers 

### ISSUE THREAD

**Issue by obedmr** [clearlinux/clear-config-management#62]
Main [README.md](https://github.com/clearlinux/clear-config-management/blob/master/examples/ciao/README.md) should only contain production deployment data. 

Need to remove any reference related to development packages or resources that are not required. 

**Example** (things to be removed from main [README.md](https://github.com/clearlinux/clear-
config-management/blob/master/examples/ciao/README.md) ):

```
Note: In order to deploy ciao from the latest development branch set ciao_dev = True in
group_vars/all file or pass the command line argument --extra-vars "ciao_dev=true"
```

And then, we need to create a development-only document.

**Comment by mrkz** [comment]
This is done in https://github.com/01org/ciao/wiki/Automated-Ciao-Multinode-Development-and-Test-Environment already, published as a draft as further review is needed (yet, instructions are the same as [README.md](https://github.com/clearlinux/clear-config-management/blob/master/examples/ciao/README.md) except the `ciao_dev=true` option is specified
