### ISSUE TITLE
documentation: Fedora requires firewall to be configured

### ISSUE THREAD

**Issue by obedmr** [clearlinux/clear-config-management#65]
Examples:
- Firewall rules for Fedora24 need to be configured before

**Comment by albertomurillo** [comment]
@erick0z What are the firewall rules that have to be configured for fedora 24?

**Comment by albertomurillo** [comment]
This info can be put here https://github.com/clearlinux/clear-config-management/blob/master/examples/ciao/doc/requirements.md#fedora

**Comment by albertomurillo** [comment]
We can do two options:
1) Document that the sysadmin should disable the fedora firewall
2) Add a task to ciao-common to disable the firewall when the os is fedora

@mcastelino @obedmr Are you ok if we go with 2?

**Comment by albertomurillo** [comment]
Closing this with https://github.com/clearlinux/clear-config-management/commit/e9db0cf8583a240c764946befdd28b97b8c0d5d4
