### ISSUE TITLE
ciao: ciao-webui container fail to start in clearlinux

### ISSUE THREAD

**Issue by arturo-garcia-garcia** [clearlinux/clear-config-management#66]
when running the ciao installation using ansible in clearlinux, it fails in the step to launch the container the will host the ciao-webui

NOTE: the container that host keystone is started without problems

here is the ansible output

TASK [clearlinux.ciao-webui : Create a local certificates directory if it does not exist] ***
ok: [keystone.example.com -> localhost]

TASK [clearlinux.ciao-webui : Create self-signed SSL cert] *********************
ok: [keystone.example.com -> localhost]

TASK [clearlinux.ciao-webui : Copy certificates] *******************************
ok: [keystone.example.com] => (item=ciao-webui-key.pem)
ok: [keystone.example.com] => (item=ciao-webui-cert.pem)

TASK [clearlinux.ciao-webui : Start ciao-webui container] **********************
fatal: [keystone.example.com]: FAILED! => {"changed": false, "failed": true, "msg": "Error starting container 3cdc1a1b2a68eb3907333682cc2e2b35a6d9a9b6b3ae95402fe8f7a28bcf5f7d: 500 Server Error: Internal Server E
rror (\"containerd: container not started\")"}

here is the docker-cor configuration

root@keystone.example.com ~/ciao # cat /etc/systemd/system/docker-cor.service.d/clear-containers.conf
[Service]
ExecStart=
ExecStart=/usr/bin/dockerd --add-runtime cor=/usr/bin/cc-oci-runtime --add-runtime cor2=/root/cc-oci-runtime.sh --default-runtime=cor -H fd:// --storage-driver=overlay
TasksMax=infinity

**Comment by obedmr** [comment]
@arturo-garcia-garcia could you please test running ciao-webui container alone and verify if the issues in in ciao-webui code or if it's a deployment issue.

**Comment by albertomurillo** [comment]
Are you using clear containers?
Can you verify the version of clear containers used can hanlde volumes (-v option)

**Comment by arturo-garcia-garcia** [comment]
@obedmr I tested to launch the webui container alone in Clearlinux and it works fine, looks like an issue in the deployment process, I use this command to launch it 
`
 docker run -v`pwd`/webui_key.pem:/etc/pki/ciao-webui-key.pem \
               -v`pwd`/webui_cert.pem:/etc/pki/ciao-webui-cert.pem \
               -e CONTROLLER_HOST=controller.example.com \
               -e IDENTITY_HOST=keystone.example.com \
               -e no_proxy=example.com,.example.com \
               -p 443:443 -d clearlinux/ciao-webui
`

@albertomurillo Yes, I'm using Clear containers, and it can handle volumes, as you can see in the code above, also is used for launch the keystone container and it work fine, here is how I launch it 
`
docker run -d -it --name keystone -p 5000:5000 -p 35357:35357 \
           -e IDENTITY_HOST="keystone.example.com" \
           -e KEYSTONE_ADMIN_PASSWORD="secret" \
           -e no_proxy=example.com,.example.com \
           -v`pwd`/keystone_cert.pem:/etc/nginx/ssl/keystone_cert.pem \
           -v`pwd`/keystone_key.pem:/etc/nginx/ssl/keystone_key.pem \
           -v /etc/hosts:/etc/hosts \
           --runtime=runc \
           clearlinux/keystone
`

**Comment by albertomurillo** [comment]
It actually does start with the playbooks scripts and manually in clearlinux using clearcontainers...
but it dies shortly after.

So from the point of view of the playbooks, there isn't a bug in the deployment scripts.

The container should be investigated tou

**Comment by arturo-garcia-garcia** [comment]
@albertomurillo @obedmr 
I run the docker logs on the webui container and it seems like there is an issue with the process that start the webui
`
root@keystone.intel.com ~/docker_test # docker logs --details condescending_hawking
 production
 production_template.ejs

> ciao-webui@1.0.0 start /ciao-webui
> node ./bin/www "production"

 /ciao-webui/core/ciao_adapter.js:13
         this.host = config.host;
                           ^

 TypeError: Cannot read property 'host' of undefined
     at ciaoAdapter.setup (/ciao-webui/core/ciao_adapter.js:13:27)
     at ciaoAdapter.useNode (/ciao-webui/core/ciao_adapter.js:32:8)
     at Object.<anonymous> (/ciao-webui/routes/data.js:18:45)
     at Module._compile (module.js:556:32)
     at Object.Module._extensions..js (module.js:565:10)
     at Module.load (module.js:473:32)
     at tryModuleLoad (module.js:432:12)
     at Function.Module._load (module.js:424:3)
     at Module.require (module.js:483:17)
     at require (internal/module.js:20:19)

 npm ERR! Linux 4.5.0-49.container
 npm ERR! argv "/usr/bin/node" "/usr/sbin/npm" "start" "--" "production"
 npm ERR! node v6.6.0
 npm ERR! npm  v3.10.3
 npm ERR! code ELIFECYCLE
 npm ERR! ciao-webui@1.0.0 start: `node ./bin/www "production"`
 npm ERR! Exit status 1
 npm ERR! 
 npm ERR! Failed at the ciao-webui@1.0.0 start script 'node ./bin/www "production"'.
 npm ERR! Make sure you have the latest version of node.js and npm installed.
 npm ERR! If you do, this is most likely a problem with the ciao-webui package,
 npm ERR! not with npm itself.
 npm ERR! Tell the author that this fails on your system:
 npm ERR!     node ./bin/www "production"
 npm ERR! You can get information on how to open an issue for this project with:
 npm ERR!     npm bugs ciao-webui
 npm ERR! Or if that isn't available, you can get their info via:
 npm ERR!     npm owner ls ciao-webui
 npm ERR! There is likely additional logging output above.

 npm ERR! Please include the following file with any support request:
 npm ERR!     /ciao-webui/npm-debug.log
`

I think is need to check if there is a change on this process that need to be updated in the container

**Comment by arturo-garcia-garcia** [comment]
sorry, my mouse moves over the wrong button :S

**Comment by mrkz** [comment]
Tested with build https://hub.docker.com/r/clearlinux/ciao-webui/builds/bzu2wcsl2qbsjuvpt3vrrza/
And got successful response from the ciao-webui container:

```
# curl -L https://controller.example.com/ --insecure                                      
<!DOCTYPE html>
<html>
  <head>
    <meta charset="utf-8">
    <title>CIAO</title><link rel='stylesheet' href='/bootstrap/dist/css/bootstrap.min.css' /><link rel='stylesheet' href='/stylesheets/framework.css' /><link rel='stylesheet' href='/stylesheets/d3Framework.css' /><script type='text/javasc
ript' src='/jquery/dist/jquery.js'></script><script type='text/javascript' src='/jquery-ui/jquery-ui.js'></script><script type='text/javascript' src='/data/dataManager.js'></script><script type='text/javascript'>window.datamanager.loadDat
a(({}));</script><script type='text/javascript' src='/javascripts/library/validations.js'></script>
  </head>
  <body>

    <div class="main-container container">
      <!-- Logger container: base style is alert and is hidden by default -->
      <div id="logger" class="alert hidden"></div>
      <!-- default template accepts page path to include -->
      <div id="main-top-navbar"></div>
<div id="login-container"></div>
    </div>

    <!-- this template loads JS files passed on the "scripts" array -->

    <script type="text/javascript" src="/javascripts/bundle_login.js"></script>

  </body>
</html>
```

**Comment by albertomurillo** [comment]
The new container works on my cluster too

**Comment by arturo-garcia-garcia** [comment]
Hi @albertomurillo , @mrkz , @obedmr  I retest the webui container alone and installing ciao directly (not using the ciao-deploy process) and it works fine now. I'm closing this issue, thanks
