### ISSUE TITLE
cleanup: fail when trying to uninstall some ClearLinux bundles

### ISSUE THREAD

**Issue by erick0z** [clearlinux/clear-config-management#74]
swupd fails when trying to uninstall the following bundles:
- kvm-host
- libXclient
- kernel-container
- network-advanced
- storage-utils

swupd throws the following error
"Error: bundle requested to be removed is required by other installed bundles"
Perhaps the order of the bundles to remove is causing this issue.

**Comment by albertomurillo** [comment]
Its failing to uninstall storage utils which is required by ceph.

Uninstall storage-cluster (ceph) bundle from clearlinux and ceph packages from ubuntu and fedora too
