### ISSUE TITLE
Error while downloading the clearlinux images for docker-hub

### ISSUE THREAD

**Issue by arturo-garcia-garcia** [clearlinux/clear-config-management#81]
When trying to download the images from docker-hub, the job fails with this message

`
 TASK [Check container images have been downloaded] *****************************
# failed: [clr-4f02e4831ba5447cac806812d5ac78cc.intel.com](item={'_ansible_parsed': True, '_ansible_no_log': False, u'ansible_job_id': u'278039830070.109614', u'started': 1, '_ansible_item_result': True, 'item': u'clearlinux/keystone', u'finished': 0, u'results_file': u'/root/.ansible_async/278039830070.109614'}) => {"ansible_job_id": "278039830070.109614", "changed": false, "failed": true, "finished": 1, "item": {"ansible_job_id": "278039830070.109614", "finished": 0, "item": "clearlinux/keystone", "results_file": "/root/.ansible_async/278039830070.109614", "started": 1}, "msg": "Error pulling clearlinux/keystone - code: None message: Error while pulling image: Get https://index.docker.io/v1/repositories/clearlinux/keystone/images: x509: certificate signed by unknown authority"}
# FAILED - RETRYING: TASK: Check container images have been downloaded (1800 retries left).
# failed: [clr-4f02e4831ba5447cac806812d5ac78cc.intel.com](item={'_ansible_parsed': True, '_ansible_no_log': False, u'ansible_job_id': u'838903796424.109649', u'started': 1, '_ansible_item_result': True, 'item': u'clearlinux/ciao-webui', u'finished': 0, u'results_file': u'/root/.ansible_async/838903796424.109649'}) => {"ansible_job_id": "838903796424.109649", "changed": false, "failed": true, "finished": 1, "item": {"ansible_job_id": "838903796424.109649", "finished": 0, "item": "clearlinux/ciao-webui", "results_file": "/root/.ansible_async/838903796424.109649", "started": 1}, "msg": "Error pulling clearlinux/ciao-webui - code: None message: Error while pulling image: Get https://index.docker.io/v1/repositories/clearlinux/ciao-webui/images: x509: certificate signed by unknown authority"}

`

**Comment by albertomurillo** [comment]
Have you tried manually running
docker pull clearlinux/ciao-webui ?

**Comment by mrkz** [comment]
This looks related to https://github.com/docker/docker/issues/8849

**Comment by albertomurillo** [comment]
docker looks for certificates at /etc/ssl/certs which from clearlinux 10910 its a symlink to /var/cache/ca-certs.

https://github.com/clearlinux/clear-config-management/commit/a53d5c56bc5bbba60013ff0e65dbb75f7812da1c stops creating the /etc/ssl/certs directory since it was preventing systemd to create the symlink mentioned before.
