### ISSUE TITLE
TASK [clearlinux.keystone : Create self-signed SSL cert]  Fails

### ISSUE THREAD

**Issue by arturo-garcia-garcia** [clearlinux/clear-config-management#83]
when running the ansible installation, it fails with the next error message

`
TASK [clearlinux.keystone : Create a local certificates directory if it does not exist] ***
task path: /etc/ansible/roles/clearlinux.keystone/tasks/certificates.yml:16
<localhost> ESTABLISH LOCAL CONNECTION FOR USER: root
<localhost> EXEC /bin/sh -c 'LANG=en_US.UTF-8 LC_ALL=en_US.UTF-8 LC_MESSAGES=en_US.UTF-8 /usr/bin/python2 && sleep 0'
changed: [controller.example.com -> localhost] => {"changed": true, "diff": {"after": {"path": "certificates/keystone", "state": "directory"}, "before": {"path": "certificates/keystone", "state": "absent"}}, "gid": 0, "group": "root", "invocation": {"module_args": {"backup": null, "content": null, "delimiter": null, "diff_peek": null, "directory_mode": null, "follow": false, "force": false, "group": null, "mode": null, "original_basename": null, "owner": null, "path": "certificates/keystone", "recurse": false, "regexp": null, "remote_src": null, "selevel": null, "serole": null, "setype": null, "seuser": null, "src": null, "state": "directory", "validate": null}, "module_name": "file"}, "mode": "0755", "owner": "root", "path": "certificates/keystone", "size": 4096, "state": "directory", "uid": 0}

TASK [clearlinux.keystone : Create self-signed SSL cert] ***********************
task path: /etc/ansible/roles/clearlinux.keystone/tasks/certificates.yml:20
<localhost> ESTABLISH LOCAL CONNECTION FOR USER: root
<localhost> EXEC /bin/sh -c 'LANG=en_US.UTF-8 LC_ALL=en_US.UTF-8 LC_MESSAGES=en_US.UTF-8 /usr/bin/python2 && sleep 0'
fatal: [controller.example.com -> localhost]: FAILED! => {"changed": false, "cmd": "openssl req -new -nodes -x509 -subj /CN=controller.example.com -days 365 -keyout certificates/keystone/keystone_key.pem -out certificates/keystone/keystone_cert.pem -extensions v3_ca", "failed": true, "invocation": {"module_args": {"_raw_params": "openssl req -new -nodes -x509 -subj \"/CN=controller.example.com\" -days 365 -keyout certificates/keystone/keystone_key.pem -out certificates/keystone/keystone_cert.pem -extensions v3_ca", "_uses_shell": false, "chdir": null, "creates": "certificates/keystone/keystone_key.pem", "executable": null, "removes": null, "warn": true}, "module_name": "command"}, "msg": "[Errno 2] No such file or directory", "rc": 2}

NO MORE HOSTS LEFT *************************************************************

`

**Comment by mrkz** [comment]
This is due to missing `openssl` command in the ciao-deploy container

**Comment by mrkz** [comment]
This should be fixed now with the build https://hub.docker.com/r/clearlinux/ciao-deploy/builds/bhxo8lff7e8sdr4yucvvoea/ which pulls Dockerfile with the fix: https://github.com/clearlinux/dockerfiles/commit/853b44aa2d1b6aa485fcf0b3e6317f6ddbb14f58

**Comment by albertomurillo** [comment]
@arturo-garcia-garcia  can you verify and close?

**Comment by arturo-garcia-garcia** [comment]
Hi @mrkz , @albertomurillo

I test again pulling the latest image from dockerhub and the error is gone, I'm closing this issue
