### ISSUE TITLE
docker keystone image isn't started after reboot

### ISSUE THREAD

**Issue by rbradford** [clearlinux/clear-config-management#85]
After rebooting the controller node the docker container for ciao-keystone doesn't come up. This should probably be a .service file so that the the ciao-controller.service can depend on it.

**Comment by albertomurillo** [comment]
Docker should be configure to restart instances after a reboot.
https://docs.docker.com/engine/admin/host_integration/

**Comment by albertomurillo** [comment]
ciao-webui role has the same problem
