### ISSUE TITLE
Workloads for ciao-controller need to be resynced with ciao

### ISSUE THREAD

**Issue by rbradford** [clearlinux/clear-config-management#88]
In particular the boot from volume workload is missing.

**Comment by albertomurillo** [comment]
Hardcoded workloads is something we should get rid off in both ciao and ansible scripts.

In the meantime, Are the worklaods modified often?

**Comment by albertomurillo** [comment]
Also, https://github.com/01org/ciao/tree/master/ciao-controller/tables have not been changed.

Im syncing ciao-controller/tables and ciao-controller/workloads  is there another folder I'm missing?

**Comment by rbradford** [comment]
Ah. I was testing with https://github.com/01org/ciao/pull/625/commits which hasn't yet landed....

**Comment by albertomurillo** [comment]
Ok, I will leave this issue open until https://github.com/01org/ciao/pull/625 is landed

**Comment by albertomurillo** [comment]
This is fixed with https://github.com/01org/ciao/pull/766/commits/8a6c04388141290cf96df4cf07cdc2ecc54c3fc0
