### ISSUE TITLE
Ansible fails creating keystone projects in first run

### ISSUE THREAD

**Issue by arturo-garcia-garcia** [clearlinux/clear-config-management#92]
When running ansible for the ciao-deploy, the first time , it fails when create custom projects, and when rerun ansible, it pass that step but fails when trying to mount the cnci image, here are the outputs for each run
[http://hastebin.com/tuxosuloba.cs](url)

**Comment by mrkz** [comment]
The hastebin link provided has expired now, please push the full log in the issue description instead.

**Comment by arturo-garcia-garcia** [comment]
Hi  @mrkz , here are the logs

First Run
`
TASK [clearlinux.keystone : Wait for keystone to be ready] *********************
task path: /etc/ansible/roles/clearlinux.keystone/tasks/access.yml:16
<controller.example.com> ESTABLISH LOCAL CONNECTION FOR USER: root
<controller.example.com> EXEC /bin/sh -c 'LANG=en_US.UTF-8 LC_ALL=en_US.UTF-8 LC_MESSAGES=en_US.UTF-8 /usr/bin/python && sleep 0'
ok: [controller.example.com] => {"changed": false, "elapsed": 0, "invocation": {"module_args": {"connect_timeout": 5, "delay": 0, "exclude_hosts": null, "host": "controller.example.com", "path": null, "port": 5000, "search_regex": null, $

TASK [clearlinux.keystone : Create custom services] ****************************
task path: /etc/ansible/roles/clearlinux.keystone/tasks/access.yml:19

TASK [clearlinux.keystone : Create custom projects] ****************************
task path: /etc/ansible/roles/clearlinux.keystone/tasks/access.yml:32
<controller.example.com> ESTABLISH LOCAL CONNECTION FOR USER: root
<controller.example.com> EXEC /bin/sh -c 'LANG=en_US.UTF-8 LC_ALL=en_US.UTF-8 LC_MESSAGES=en_US.UTF-8 /usr/bin/python && sleep 0'
An exception occurred during task execution. The full traceback is:
Traceback (most recent call last):
  File "/tmp/ansible_Cj9N96/ansible_module_keystone.py", line 1424, in <module>
    main()
  File "/tmp/ansible_Cj9N96/ansible_module_keystone.py", line 1418, in main
    km.command_router()
  File "/tmp/ansible_Cj9N96/ansible_module_keystone.py", line 479, in command_router
    facts = action(variables=action_command['variables'])
  File "/tmp/ansible_Cj9N96/ansible_module_keystone.py", line 669, in ensure_project
    self._authenticate()
  File "/tmp/ansible_Cj9N96/ansible_module_keystone.py", line 595, in _authenticate
    project_domain_name=project_domain_name,
  File "/usr/lib/python2.7/site-packages/keystoneclient/v3/client.py", line 226, in __init__
    self.authenticate()
  File "/usr/lib/python2.7/site-packages/positional/**init**.py", line 101, in inner
    return wrapped(_args, *_kwargs)
  File "/usr/lib/python2.7/site-packages/keystoneclient/httpclient.py", line 584, in authenticate
    resp = self.get_raw_token_from_identity_service(**kwargs)
  File "/usr/lib/python2.7/site-packages/keystoneclient/v3/client.py", line 311, in get_raw_token_from_identity_service
    _('Authorization failed: %s') % e)
keystoneauth1.exceptions.auth.AuthorizationFailure: Authorization failed: SSL exception connecting to https://controller.example.com:35357/v3/auth/tokens: EOF occurred in violation of protocol (_ssl.c:590)
failed: [controller.example.com](item={u'project': u'demo', u'description': u'Demo Project'}) => {"failed": true, "invocation": {"module_name": "keystone"}, "item": {"description": "Demo Project", "project": "demo"}, "module_stderr": "T$
<controller.example.com> EXEC /bin/sh -c 'LANG=en_US.UTF-8 LC_ALL=en_US.UTF-8 LC_MESSAGES=en_US.UTF-8 /usr/bin/python && sleep 0'
An exception occurred during task execution. The full traceback is:
Traceback (most recent call last):
  File "/tmp/ansible_1MCiP5/ansible_module_keystone.py", line 1424, in <module>
    main()
  File "/tmp/ansible_1MCiP5/ansible_module_keystone.py", line 1418, in main
    km.command_router()
  File "/tmp/ansible_1MCiP5/ansible_module_keystone.py", line 479, in command_router
    facts = action(variables=action_command['variables'])
  File "/tmp/ansible_1MCiP5/ansible_module_keystone.py", line 669, in ensure_project
    self._authenticate()
  File "/tmp/ansible_1MCiP5/ansible_module_keystone.py", line 595, in _authenticate
    project_domain_name=project_domain_name,
  File "/usr/lib/python2.7/site-packages/keystoneclient/v3/client.py", line 226, in __init__
    self.authenticate()
  File "/usr/lib/python2.7/site-packages/positional/**init**.py", line 101, in inner
    return wrapped(_args, *_kwargs)
  File "/usr/lib/python2.7/site-packages/keystoneclient/httpclient.py", line 584, in authenticate
    resp = self.get_raw_token_from_identity_service(**kwargs)
  File "/usr/lib/python2.7/site-packages/keystoneclient/v3/client.py", line 311, in get_raw_token_from_identity_service
    _('Authorization failed: %s') % e)
keystoneauth1.exceptions.auth.AuthorizationFailure: Authorization failed: SSL exception connecting to https://controller.example.com:35357/v3/auth/tokens: EOF occurred in violation of protocol (_ssl.c:590)
failed: [controller.example.com](item={u'project': u'service', u'description': u'Service Project'}) => {"failed": true, "invocation": {"module_name": "keystone"}, "item": {"description": "Service Project", "project": "service"}, "module$

NO MORE HOSTS LEFT *************************************************************
    to retry, use: --limit @/root/ciao/ciao.retry

PLAY RECAP *********************************************************************
controller.example.com          : ok=21   changed=6    unreachable=0    failed=1

`

Second Run

`
TASK [clearlinux.ciao-controller : Find available loop device] *****************
task path: /etc/ansible/roles/clearlinux.ciao-controller/tasks/create_cnci_image.yml:45
<controller.example.com> ESTABLISH LOCAL CONNECTION FOR USER: root
<controller.example.com> EXEC /bin/sh -c 'LANG=en_US.UTF-8 LC_ALL=en_US.UTF-8 LC_MESSAGES=en_US.UTF-8 /usr/bin/python && sleep 0'
changed: [controller.example.com] => {"changed": true, "cmd": ["losetup", "-f"], "delta": "0:00:00.006384", "end": "2016-10-13 20:52:07.331974", "invocation": {"module_args": {"_raw_params": "losetup -f", "_uses_shell": false, "chdir": n$

TASK [clearlinux.ciao-controller : Mount cnci image on loop] *******************
task path: /etc/ansible/roles/clearlinux.ciao-controller/tasks/create_cnci_image.yml:50
<controller.example.com> ESTABLISH LOCAL CONNECTION FOR USER: root
<controller.example.com> EXEC /bin/sh -c 'LANG=en_US.UTF-8 LC_ALL=en_US.UTF-8 LC_MESSAGES=en_US.UTF-8 /usr/bin/python && sleep 0'
changed: [controller.example.com] => {"changed": true, "cmd": ["losetup", "/dev/loop1", "-P", "images/clear-8260-ciao-networking.img"], "delta": "0:00:00.023837", "end": "2016-10-13 20:52:07.500341", "invocation": {"module_args": {"_raw_$

TASK [clearlinux.ciao-controller : Mounting cnci image in /mnt/tmp] ************
task path: /etc/ansible/roles/clearlinux.ciao-controller/tasks/create_cnci_image.yml:54
<controller.example.com> ESTABLISH LOCAL CONNECTION FOR USER: root
<controller.example.com> EXEC /bin/sh -c 'LANG=en_US.UTF-8 LC_ALL=en_US.UTF-8 LC_MESSAGES=en_US.UTF-8 /usr/bin/python && sleep 0'
fatal: [controller.example.com]: FAILED! => {"changed": false, "failed": true, "invocation": {"module_args": {"dump": null, "fstab": "/etc/fstab", "fstype": "ext4", "name": "/mnt/tmp", "opts": null, "passno": null, "src": "/dev/loop1p2",$

NO MORE HOSTS LEFT *************************************************************
    to retry, use: --limit @/root/ciao/ciao.retry

PLAY RECAP *********************************************************************
controller.example.com          : ok=54   changed=16   unreachable=0    failed=1
`

**Comment by albertomurillo** [comment]
After TASK [clearlinux.ciao-controller : Mounting cnci image in /mnt/tmp] fails.
Are you able to manually mount the second partition of the image?

**Comment by arturo-garcia-garcia** [comment]
I try to mount it manually and it fails, when i check the loops device,  the 2nd partition does not exist

`
root@21d3a7ceb898 /root/ciao # losetup 
NAME       SIZELIMIT OFFSET AUTOCLEAR RO BACK-FILE                                        DIO
/dev/loop1         0      0         0  0 /root/ciao/images/clear-8260-ciao-networking.img   0
/dev/loop0         0      0         0  0 /root/ciao/images/clear-8260-ciao-networking.img   0
`

`
root@21d3a7ceb898 /root/ciao # mount /dev/loop0p2 /mnt/tmp
mount: special device /dev/loop0p2 does not exist
root@21d3a7ceb898 /root/ciao # mount /dev/loop1p2 /mnt/tmp
mount: special device /dev/loop1p2 does not exist
root@21d3a7ceb898 /root/ciao # 
`

**Comment by arturo-garcia-garcia** [comment]
@albertomurillo @mrkz 
Injust retest with release 11080 and still failing, I try to remove the used loop devices and retry the installation and still failing the same way, I'm not able to manually mount the 2nd partition of the image, it is not listed, looks like an issue mounting the image

**Comment by arturo-garcia-garcia** [comment]
@mrkz @albertomurillo 
Update, I ran a cleanup in the env and then retry, cleaning the loop devices before the 2nd run, and this time succeed to mount the image, but fails trying to copy the ciao_cnci_agent in to the cnci_image
`
TASK [clearlinux.ciao-controller : Mounting cnci image in /mnt/tmp] ************
task path: /etc/ansible/roles/clearlinux.ciao-controller/tasks/create_cnci_image.yml:54
<controller.example.com> ESTABLISH LOCAL CONNECTION FOR USER: root
<controller.example.com> EXEC /bin/sh -c 'LANG=en_US.UTF-8 LC_ALL=en_US.UTF-8 LC_MESSAGES=en_US.UTF-8 /usr/bin/python && sleep 0'
changed: [controller.example.com] => {"changed": true, "fstab": "/etc/fstab", "fstype": "ext4", "invocation": {"module_args": {"dump": null, "fstab": "/etc/fstab", "fstype": "ext4", "name": "/mnt/tmp", "opts": null, "passno": null, "src": "/dev/loop0p2", "state": "mounted"}, "module_name": "mount"}, "name": "/mnt/tmp", "src": "/dev/loop0p2"}

TASK [clearlinux.ciao-controller : Set ciao-cnci-agent location] ***************
task path: /etc/ansible/roles/clearlinux.ciao-controller/tasks/create_cnci_image.yml:62
ok: [controller.example.com] => {"ansible_facts": {"ciao_cnci_agent": "fetch/ciao-cnci-agent"}, "changed": false, "invocation": {"module_args": {"ciao_cnci_agent": "fetch/ciao-cnci-agent"}, "module_name": "set_fact"}}

TASK [clearlinux.ciao-controller : Copy ciao_cnci_agent to cnci image] *********
task path: /etc/ansible/roles/clearlinux.ciao-controller/tasks/create_cnci_image.yml:65
<controller.example.com> ESTABLISH LOCAL CONNECTION FOR USER: root
<controller.example.com> EXEC /bin/sh -c 'LANG=en_US.UTF-8 LC_ALL=en_US.UTF-8 LC_MESSAGES=en_US.UTF-8 /usr/bin/python && sleep 0'
fatal: [controller.example.com]: FAILED! => {"changed": true, "cmd": "sudo cp fetch/ciao-cnci-agent /mnt/tmp/usr/bin/", "delta": "0:00:00.006981", "end": "2016-10-18 21:33:20.287219", "failed": true, "invocation": {"module_args": {"_raw_params": "sudo cp fetch/ciao-cnci-agent /mnt/tmp/usr/bin/", "_uses_shell": true, "chdir": null, "creates": "/mnt/tmp/usr/bin/ciao-cnci-agent", "executable": null, "removes": null, "warn": true}, "module_name": "command"}, "rc": 127, "start": "2016-10-18 21:33:20.280238", "stderr": "/bin/sh: sudo: command not found", "stdout": "", "stdout_lines": [], "warnings": ["Consider using 'become', 'become_method', and 'become_user' rather than running sudo"]}

NO MORE HOSTS LEFT *************************************************************
        to retry, use: --limit @/root/ciao/ciao.retry

PLAY RECAP *********************************************************************
controller.example.com          : ok=56   changed=17   unreachable=0    failed=1

`

**Comment by albertomurillo** [comment]
This issue will be use to track the first problem (unable to create keystone projects on the first run)

For the task failing to copy ciao-cnci-agent inside the cnci image i have opened
https://github.com/clearlinux/clear-config-management/issues/97

**Comment by albertomurillo** [comment]
This happens only when running the keystone container in clear-containers.

Before task "Create custom services"
Another task is run to ensure port 5000 is up

```
  - name: Wait for keystone to be ready
    wait_for: host="{{ keystone_fqdn }}" port=5000 state=started
```

It seems like clear-containers opens the port event when the app has not finished starting

**Comment by albertomurillo** [comment]
Issue open at https://github.com/01org/cc-oci-runtime/issues/349

**Comment by albertomurillo** [comment]
Tracking at https://github.com/01org/ciao/issues/788
