### ISSUE TITLE
ciao-deployment: Migrate all ciao related work to official CIAO project area

### ISSUE THREAD

**Issue by obedmr** [clearlinux/clear-config-management#93]
Migrate all ciao related playbooks to https://github.com/01org/ciao

**Comment by albertomurillo** [comment]
Where should this be moved?
ciao/_DeploymentAndDistroPackaging/ansible ?

**Comment by obedmr** [comment]
@albertomurillo yes.

**Comment by albertomurillo** [comment]
PR: https://github.com/01org/ciao/pull/766/

**Comment by albertomurillo** [comment]
Done in https://github.com/01org/ciao/commit/497f542435574c0fc0bf09f4d02e8e1e4bf61e64
