### ISSUE TITLE
Update docker containers to latest version

### ISSUE THREAD

**Issue by albertomurillo** [clearlinux/clear-config-management#98]
When ansible runs, it should download the latest version of docker containers
- clearlinux/keystone
- clearlinux/ciao-webui

If the container got updated, remove the old container and start the new version

**Comment by mrkz** [comment]
I guess we would be using the `pull` parameter for the ansible [docker_module](http://docs.ansible.com/ansible/docker_module.html) to update the docker image to the latest, notice that this would increase deployment times when the docker image needs to be updated.

For the removal of old container and start of new one with latest release, I've found this solution in [Stackoverflow](http://stackoverflow.com/questions/26423515/how-to-automatically-update-your-docker-containers-if-base-images-are-updated#26548914) which basically checks the hash for the image  running in the container and the hash from latest docker image of container:

```
#!/usr/bin/env bash
set -e
BASE_IMAGE="registry"
REGISTRY="registry.hub.docker.com"
IMAGE="$REGISTRY/$BASE_IMAGE"
CID=$(docker ps | grep $IMAGE | awk '{print $1}')
docker pull $IMAGE

for im in $CID
do
    LATEST=`docker inspect --format "{{.Id}}" $IMAGE`
    RUNNING=`docker inspect --format "{{.Image}}" $im`
    NAME=`docker inspect --format '{{.Name}}' $im | sed "s/\///g"`
    echo "Latest:" $LATEST
    echo "Running:" $RUNNING
    if [ "$RUNNING" != "$LATEST" ];then
        echo "upgrading $NAME"
        stop docker-$NAME
        docker rm -f $NAME
        start docker-$NAME
    else
        echo "$NAME up to date"
    fi
done
```

**Comment by albertomurillo** [comment]
docker_image should update the image and return changed when updated or unchanged when it is already the latest image but it is always returning changed.
See https://github.com/ansible/ansible-modules-core/issues/5489

the solution would be to run `docker pull` and inspect the outoput to see if the image was indeed updated or not

**Comment by albertomurillo** [comment]
Fixed at https://github.com/01org/ciao/pull/766/commits/87f1967776d161b01d6e7c3eee11024a6cb10932
